export default [
  {
    Transaction_id: "12695juf",
    product: "Shoe",
    product_amount: 4.3,
    date: new Date().toLocaleString(),
    productStatus: "Successful",
    productAction: "mdi-eye-outline",
  },
  {
    Transaction_id: "13695juf",
    product: "IPhone X",
    product_amount: 4.3,
    date: new Date().toLocaleString(),
    productStatus: "Failed",
    productAction: "mdi-eye-outline",
  },
  {
    Transaction_id: "11695juf",
    product: "Zink",
    product_amount: 4.9,
    date: new Date().toLocaleString(),
    productStatus: "Pending",
    productAction: "mdi-eye-outline",
  },
  {
    Transaction_id: "22695juf",
    product: "IPhone X",
    product_amount: 4.3,
    date: new Date().toLocaleString(),
    productStatus: "Successful",
    productAction: "mdi-eye-outline",
  },
  {
    Transaction_id: "16695juf",
    product: "Gold bar",
    product_amount: 7,
    date: new Date().toLocaleString(),
    productStatus: "Failed",
    productAction: "mdi-eye-outline",
  },
  {
    Transaction_id: "32695juf",
    product: "Broiler Chicken",
    product_amount: 0.0,
    date: new Date().toLocaleString(),
    productStatus: "Successful",
    productAction: "mdi-eye-outline",
  },
  {
    Transaction_id: "92695juf",
    product: "Television",
    product_amount: 0,
    date: new Date().toLocaleString(),
    productStatus: "Pending",
    productAction: "mdi-eye-outline",
  },
  {
    Transaction_id: "42695juf",
    product: "Refridgirator",
    product_amount: 6.5,
    date: new Date().toLocaleString(),
    productStatus: "Successful",
    productAction: "mdi-eye-outline",
  },
  {
    Transaction_id: "52695juf",
    product: "Gold bar",
    product_amount: 7,
    date: new Date().toLocaleString(),
    productStatus: "Successful",
    productAction: "mdi-eye-outline",
  },
  {
    Transaction_id: "62695juf",
    product: "Bag",
    product_amount: 4.0,
    date: new Date().toLocaleString(),
    productStatus: "Pending",
    productAction: "mdi-eye-outline",
  },
  {
    Transaction_id: "72695juf",
    product: "Apple",
    product_amount: 6.0,
    date: new Date().toLocaleString(),
    productStatus: "Pending",
    productAction: "mdi-eye-outline",
  },
  {
    Transaction_id: "15695juf",
    product: "Refridgirator",
    product_amount: 6.5,
    date: new Date().toLocaleString(),
    productStatus: "Failed",
    productAction: "mdi-eye-outline",
  },
  {
    Transaction_id: "82695juf",
    product: "Eva wine",
    product_amount: 3.9,
    date: new Date().toLocaleString(),
    productStatus: "Pending",
    productAction: "mdi-eye-outline",
  },
  {
    Transaction_id: "14695juf",
    product: "Broiler Chicken",
    product_amount: 0.0,
    date: new Date().toLocaleString(),
    productStatus: "Failed",
    productAction: "mdi-eye-outline",
  },
  {
    Transaction_id: "10695juf",
    product: "Zink",
    product_amount: 4.9,
    date: new Date().toLocaleString(),
    productStatus: "Pending",
    productAction: "mdi-eye-outline",
  },
  {
    Transaction_id: "12695juf",
    product: "Shoe",
    product_amount: 4.3,
    date: new Date().toLocaleString(),
    productStatus: "Failed",
    productAction: "mdi-eye-outline",
  },
]
